<HTML>
		<HEAD>
		</HEAD>
		<BODY>

			WELCOME

			<FORM>
				NOMBRE: <INPUT TYPE="TEXT" NAME="NOMBRE"/>
				APELLIDO: <INPUT TYPE="TEXT" NAME="APELLIDO"/>
				PASSWORD: <INPUT TYPE="PASSWORD" NAME="PASSW"/>
			</FORM>

		</BODY>

</HTML>